Models/Add_Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Online_Book_Store.Models
{
    public class Book_Category
    {
        [Key]
        public int cid { get; set; }
        [Required]
        public string Category { get; set; }

        public ICollection<Add_Book> ab { get; set; }
    }
    public class Add_Book
    {
        public int id { get; set; }

        [Required]
        public string bname { get; set; }

        [Required]
        public string btitle { get; set; }

        [Required]
        public string author { get; set; }

        [Required]
        public string publication { get; set; }

        [Required]
        public double price { get; set; }

        public string b_img { get; set; }

        public string b_file { get; set; }

        public int cid { get; set; }
        public virtual Book_Category b { get; set; }

    }
}

Controllers/AddBookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Book_Store.Models;

namespace Online_Book_Store.Controllers
{
    public class AddBookController : Controller
    {
        private Context db = new Context();


        public ActionResult Create()
        {
            ViewBag.cid = new SelectList(db.Book_Category, "cid", "Category");
            return View();
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase fuimg, HttpPostedFileBase fufile,Add_Book add_book)
        {
            if (ModelState.IsValid)
            {
                String path = Request.PhysicalApplicationPath + @"\Book_img\";
                fuimg.SaveAs(path + "\\" + fuimg.FileName);
                add_book.b_img = fuimg.FileName.ToString();

                String path1 = Request.PhysicalApplicationPath + @"\Book\";
                fufile.SaveAs(path1 + "\\" + fufile.FileName);
                add_book.b_file = fufile.FileName.ToString();

                db.Add_Book.Add(add_book);
                db.SaveChanges();
               // return RedirectToAction("Index");
            }

            ViewBag.cid = new SelectList(db.Book_Category, "cid", "Category", add_book.cid);
            return View(add_book);
        }

    }
}

Controllers/AdminLoginController.cs
using Online_Book_Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Online_Book_Store.Controllers
{
    public class AdminLoginController : Controller
    {
        Context db = new Context();
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(AdminLogin a)
        {
            var data = from user in db.admin where user.username == a.username && user.password == a.password select user;
            if (data.Count() == 1)
            {
                Session["admin_name"] = a.username;
                return RedirectToAction("create", "AddBook");
            }
            else
            {
                Response.Write("Invalid username or password");
            }            

            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            Session.Clear();
            Session.RemoveAll();
            Session.Remove("admin_name");
            return RedirectToAction("Login");
        }

    }
}

Controllers/BookCategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Book_Store.Models;

namespace Online_Book_Store.Controllers
{
    public class BookCategoryController : Controller
    {
        private Context db = new Context();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Book_Category book_category)
        {
            if (ModelState.IsValid)
            {
                db.Book_Category.Add(book_category);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            return View(book_category);
        }
    }
}

Controllers/ShowFeedbackController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Book_Store.Models;

namespace Online_Book_Store.Controllers
{
    public class ShowFeedbackController : Controller
    {
        private Context db = new Context();

        public ActionResult Index()
        {
            return View(db.Feedbacks.ToList());
        }

    }
}

Views/AddBook/Create.cshtml
@model Online_Book_Store.Models.Add_Book

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    
    </style>
     <script type="text/javascript" language="javascript">
         function DisableBackButton() {
             window.history.forward()
         }
         DisableBackButton();
         window.onload = DisableBackButton;
         window.onpageshow = function (evt) { if (evt.persisted) DisableBackButton() }
         window.onunload = function () { void (0) }
</script>
</head>
<body style="background-color:white;">
    <div id="hed">
            <div class="logo">
                <a href="#">
                    <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" title="" border="0" /></a>
            </div>

            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Add book", "Create", "AddBook")</li>
                    <li>@Html.ActionLink("Add book category", "Create", "BookCategory")</li>
                    <li>@Html.ActionLink("show feedback", "Index", "ShowFeedback")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "AdminLogin")</li>
                </ul>
            </div>
        </div>
    <div style="margin-top:100px;margin-right:150px;" align="center">
    @using (Html.BeginForm("Create", "AddBook", FormMethod.Post, new { enctype = "multipart/form-data" })) {
        @Html.ValidationSummary(true)
    
        <fieldset style="width:700px;">
            <legend>Add_Book</legend>
    
            <table>
                <tr>
                    <td>
                        Book category                        
                    </td>
                    <td>
                        @Html.DropDownList("cid","---select---")
                        @Html.ValidationMessageFor(model => model.cid)
                    </td>
                </tr>
                <tr>
                    <td>
                        Book name
                    </td>
                    <td>
                        @Html.EditorFor(model => model.bname)
                        @Html.ValidationMessageFor(model => model.bname)
                    </td>
                </tr>
                <tr>
                    <td>
                        Book title    
                    </td>
                    <td>
                         @Html.EditorFor(model => model.btitle)
                         @Html.ValidationMessageFor(model => model.btitle)
                    </td>
                </tr>
                <tr>
                    <td>
                        Author
                    </td>
                    <td>
                        @Html.EditorFor(model => model.author)
                        @Html.ValidationMessageFor(model => model.author)
                    </td>
                </tr>
                <tr>
                    <td>
                        Publication name
                    </td>
                    <td>
                        @Html.EditorFor(model => model.publication)
                        @Html.ValidationMessageFor(model => model.publication)
                    </td>
                </tr>
                <tr>
                    <td>
                        Price                        
                    </td>
                    <td>
                        @Html.EditorFor(model => model.price)
                        @Html.ValidationMessageFor(model => model.price)
                    </td>
                </tr>
                <tr>
                    <td>
                         Book image
                    </td>
                    <td>
                        <input type="file" name="fuimg"/> 
                    </td>
                </tr>
                <tr>
                    <td>
                        Book file
                    </td>
                    <td>
                        <input type="file" name="fufile"/> 
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" name="Create" value="Create" />
                    </td>
                </tr>
            </table>
        </fieldset>
    }
        </div>
</body>
</html>