Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Book_Store.Models;

namespace Online_Book_Store.Controllers
{
    public class RegisterController : Controller
    {
        //private Online_Book_StoreContext db = new Online_Book_StoreContext();
        Context db = new Context();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Registrations.Add(registration);
                db.SaveChanges();
                return RedirectToAction("Login", "UserLogin");
            }

            return View(registration);
        }

    }
}

Controllers/SearchBookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Online_Book_Store.Models;

namespace Online_Book_Store.Controllers
{
    public class SearchBookController : Controller
    {
        private Context db = new Context();

       public ActionResult Index()
       {
           var display = db.Add_Book.ToList();
         
            //if (searchby="Title")
            //{
            //    return View(db.Add_BookToList().Where(x=>x.btitle.Contains(search)||search==null));
            //}

           return View(display);

             }

        public ActionResult Create()
        {
            return View(db.Add_Book.ToList());            
        }

        [HttpPost]
        public ActionResult Create(string S,string q,Add_Book add_book)
        {
            var search = from s in db.Add_Book select s;
            int id = Convert.ToInt32(Request["searchBy"]);
            //var dislay = db.Add_Book.Where(x => x.btitle.Contains(q) || x.author.Contains(q) || x.publication.Contains(q));
            //return View("Index",dislay);
            var searchParameter = "Searching";

            if (!string.IsNullOrWhiteSpace(q))
            {
                switch (id)
                {
                    case 0:
                       // int iQ = int.Parse(q);
                        search = search.Where(s => s.btitle.Contains(q));
                        searchParameter += " Book title for '" + q + "'";
                        return View("Index", search);

                    case 1:
                        search = search.Where(s => s.author.Contains(q));
                        searchParameter += " Book author for '" + q + "'";
                        return View("Index",search);

                    case 2:
                        search = search.Where(s => s.publication.Contains(q));
                        searchParameter += " Book publication for '" + q + "'";
                        return View("Index",search);
                }
            }
           else
           {
               searchParameter += "ALL";
           }
           ViewBag.SearchParameter = searchParameter;
           return View(search);

        //    if (ModelState.IsValid)
        //    {
        //        //ViewBag.search = db.Add_Book.Where(a => a.btitle == from["Search"].ToString());
        //        if (ViewBag.search!=null)
        //        {
        //            Response.Write("failed");
        //        }
        //        db.Add_Book.Add(add_book);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.cid = new SelectList(db.Book_Category, "cid", "Category", add_book.cid);
        //    return View(add_book);
        //}
    }}}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Online Book Store : @ViewBag.Title</title>
    <style type="text/css">
        #wrap {
            width: 900px;
            height: auto;
            margin: auto;
            /*background-color: #FFFFFF;*/
        }
        #hed {
          background-color:darksalmon;
            height:150px;

        }

        .footer {
            height: 100px;
            border-top: 1px #b2b2b2 dashed;
            
            background-color: white;
            width: 900px;
            margin-left: 350px;
        }
        #fot {
            background-color:ButtonText;
            margin-left: 300px;
             height: 100px;

        }
        .left_footer {
            float: right;
            padding: 10px 0 0 10px;
        }

        .right_footer {
            float:left;
            padding: 10px 10px 0 0;
        }

        .footer a {
            text-decoration: none;
            padding: 0 5px 0 5px;
            color: #afaeaf;
        }
    </style>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/jquery.autocomplete.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" ></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-latest.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/__jquery.tablesorter.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.autocomplete.min.js")"></script>
    <script type="text/javascript">
        $(function () {
            $("#Cart").tablesorter();
        });
    </script>
</head>
<body>
    <div class="wrap">
        <div id="hed">
            <div class="logo">
                <a href="#">
                    <img src="@Url.Content("~/Content/Images/logo.gif")" alt="" title="" border="0" /></a>
            </div>

            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Home", "Home", "Home")</li>
                    <li>@Html.ActionLink("Search book", "Create", "SearchBook")</li>
                    @{if(Session["email"]!=null){
                   <li>@Html.ActionLink("Cart", "Index", "ShoppingCart")</li>
                    }}
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Registration", "create", "Register")</li>
                    <li>@Html.ActionLink("Login", "Login", "UserLogin")</li>
                    <li>@Html.ActionLink("Feedback", "Create", "Feedback")</li>


                </ul>
            </div>
        </div>
        <div class="center_content">
            @RenderBody()
        </div>
        <div class="clear">
        </div>
        <div class="fot">
            <div class="left_footer">
              
            </div>
            <div class="right_footer">
                <a href="#">home</a>
                <a href="#">Serch Book</a>
                <a href="#">Registration</a>
                <a href="#">Login</a>

            </div>

        </div>
    </div>
</body>
</html>